.PHONY: test tidy

test:
	$(MAKE) -C apple test
	$(MAKE) -C droid test
	$(MAKE) -C langs test
	$(MAKE) -C frame test

tidy:
	$(MAKE) -C apple tidy
	$(MAKE) -C droid tidy
	$(MAKE) -C langs tidy
	$(MAKE) -C frame tidy
