.PHONY: all test tidy

all: test

test:
	$(MAKE) -C cpp        test
	$(MAKE) -C csharp     test
	$(MAKE) -C fsharp     test
	$(MAKE) -C go         test
	$(MAKE) -C haskell    test
	$(MAKE) -C java       test
	$(MAKE) -C kotlin     test
	$(MAKE) -C lua        test
	$(MAKE) -C node       test
	$(MAKE) -C ocaml      test
	$(MAKE) -C php        test
	$(MAKE) -C python     test
	$(MAKE) -C rust       test
	$(MAKE) -C swift      test
	$(MAKE) -C typescript test
	$(MAKE) -C v          test
	$(MAKE) -C zig        test

tidy:
	$(MAKE) -C cpp        tidy
	$(MAKE) -C csharp     tidy
	$(MAKE) -C fsharp     tidy
	$(MAKE) -C go         tidy
	$(MAKE) -C haskell    tidy
	$(MAKE) -C java       tidy
	$(MAKE) -C kotlin     tidy
	$(MAKE) -C lua        tidy
	$(MAKE) -C node       tidy
	$(MAKE) -C ocaml      tidy
	$(MAKE) -C php        tidy
	$(MAKE) -C python     tidy
	$(MAKE) -C rust       tidy
	$(MAKE) -C swift      tidy
	$(MAKE) -C typescript tidy
	$(MAKE) -C v          tidy
	$(MAKE) -C zig        tidy
