.PHONY: test tidy

test:
	$(MAKE) -C watch test
# 	$(MAKE) -C tv test
# 	$(MAKE) -C tablet test
# 	$(MAKE) -C phone test

tidy:
	$(MAKE) -C watch tidy
# 	$(MAKE) -C tv tidy
# 	$(MAKE) -C tablet tidy
# 	$(MAKE) -C phone tidy
