.PHONY: test tidy

test:
	$(MAKE) -C phone test
	$(MAKE) -C tablet test
	$(MAKE) -C tv test
	$(MAKE) -C watch test

tidy:
	$(MAKE) -C phone tidy
	$(MAKE) -C tablet tidy
	$(MAKE) -C tv tidy
	$(MAKE) -C watch tidy
